# Doc Evaluate: http://inch-ci.org
files:
  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - src/**/*.js
  # define files excluded from the analysis (defaults to [])
  excluded:
    - test/**/*.js