language: node_js
env: CI=true
sudo: false


#branches:
#  only:
#    - master

node_js:
  - "iojs"
  - "iojs-v1.7"
  - "iojs-v1.6"
  - "iojs-v1.5"
  - "iojs-v1.4"
  - "iojs-v1.3"
  - "iojs-v1.2"
  - "iojs-v1.1"
  - "iojs-v1.0"
  - "0.12"
  - "0.11"
  - "0.10"
after_script:
  - npm run coveralls
notifications:
  email:
    - qiuzhongleiabc@126.com

